import { createElement } from 'lwc';
import Search_student_component_onecomponent from 'c/search_student_component_onecomponent';

describe('c-search-student-component-onecomponent', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-search-student-component-onecomponent', {
            is: Search_student_component_onecomponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});